import Head from 'next/head';
import Header from '../components/header';

export default function DnDOfTravel() {
    return (
        <>
            <Head>
                <title>Top Travel Destinations</title>
                <meta name="Webapp sharing top travel destinations" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                <h2 className="page-heading dnd-of-travel">Do's and Dont's of Travel</h2>
                <section>
                    <table className="dnd-table">
                    <tr>
                        <th scope="col" className='tableHeading'>Do</th>
                        <th scope="col" className='tableHeading'>Dont</th>
                    </tr>
                    <tr>
                        <td className='tableData1'>Only carry as much cash as needed</td>
                        <td className='tableData2'>Carry and publicly display large amounts of money</td>
                    </tr>
                    <tr>
                        <td className='tableData1'>Be aware of your surroundings</td>
                        <td className='tableData2'>Walk with a purse or bag loosley on your shoulder</td>
                    </tr>
                    <tr>
                        <td className='tableData1'>Memorize your passport number</td>
                        <td className='tableData2'>Venture into areas known for crime/theft if there is another route</td>
                    </tr>
                    <tr>
                        <td className='tableData1'>Dress appropriately for a destination</td>
                        <td className='tableData2'>Mock, disrespect, or make fun of the local culture and people around you</td>
                    </tr>
                    </table>
                </section>
                <section className="tips">
                    <h3 id='tipsHeading'>Top Travel Tips</h3>
                    <ul>
                        <li>Eat the local foods</li>
                        <li>Travel Insurance is Everything</li>
                        <li>Spare passport photos are important</li>
                        <li>Use a daypack to keep all your importants</li>
                    </ul>
                </section>
            </main>
        </>
    )
}