import Head from 'next/head';
import Header from '../components/header';

export default function TravelCosts() {
    return (
        <>
            <Head>
                <title>Top Travel Destinations</title>
                <meta name="Webapp sharing top travel destinations" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                <h2 className="page-heading travel-costs">Travel Costs</h2>
                <section className="costs">
                    <div className='initialCosts'>
                        <p>When traveling, we all need to factor in the three largest travel expenses. <b>Transportation</b> (airfair, car rental), <b>accomodation</b> (hotels, vacation home) and,  
                        <b> sightseeing</b> (attractions, entertainment). These three factors will be the largest contributers to your travel expenses, however, they are not the only factors. It is important 
                        to remember that during your travels, it is highly likely that not everything will go as planned, ant it is important to put yourself in a position where you can afford to deal with unknown
                        situations.</p>
                    </div>
                    <div className='additionalCosts'>
                            <h4>Other travel costs may include:</h4>
                            <ul>
                            <li>Emergency expenses</li>
                            <li>Foreign transactions fees</li>
                            <li>Spontanious travel activities</li>
                            <li>Food and drinks</li>
                            <li>Vaccinations and medication</li>
                            <li>Items you forgot to bring</li>
                            <li>Local transportation costs</li>
                            <li>Mobile phone charges</li>
                            <li>Hidden hotel and resort fees</li>
                            </ul>
                        </div>
                </section>
            </main>
        </>
    )
}